# Generated by Django 3.1.7 on 2021-03-21 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'table',
            },
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.table')),
            ],
            options={
                'db_table': 'leg',
            },
        ),
        migrations.CreateModel(
            name='Feet',
            fields=[
                ('foot_id', models.AutoField(primary_key=True, serialize=False)),
                ('width', models.IntegerField(blank=True, default=None, null=True)),
                ('length', models.IntegerField(blank=True, default=None, null=True)),
                ('radius', models.IntegerField(blank=True, default=None, null=True)),
                ('leg', models.ManyToManyField(to='tables.Leg')),
            ],
            options={
                'db_table': 'feet',
            },
        ),
    ]
